// Адреси urzędów skarbowych — ЗГЕНЕРОВАНО з офіційного файлу KAS «Dane teleadresowe
// jednostek Krajowej Administracji Skarbowej» (gov.pl/web/kas/dane-teleadresowe-jednostek-kas,
// версія 03.09.2026). Ключ = назва з web/src/lib/taxOffices.ts (те, що обирає працівник в
// анкеті). 20 wyspecjalizowanych urzędów (для великих фірм) адреси у файлі не мають — їх тут
// немає, фолбек — ручне поле questionnaire.taxOfficeAddress в офісній анкеті.
// Використання: {%Urząd Skarbowy pracownika adres%} в Oświadczeniu podatkowym
// (services/contracts.ts buildContractData) — працівник адресу urzędu не знає, тому з його
// форми поле прибране (рішення 08.09.2026). Оновлення: перегенерувати з нового xlsx.
export const TAX_OFFICE_ADDRESSES: Record<string, string> = {
  "Urząd Skarbowy w Bolesławcu": "ul. Garncarska 10, 59-700 Bolesławiec",
  "Urząd Skarbowy w Bystrzycy Kłodzkiej": "ul. Adama Mickiewicza 5, 57-500 Bystrzyca Kłodzka",
  "Urząd Skarbowy w Dzierżoniowie": "ul. Pocztowa 14, 58-200 Dzierżoniów",
  "Urząd Skarbowy w Głogowie": "ul. Adama Mickiewicza 53, 67-200 Głogów",
  "Urząd Skarbowy w Jaworze": "ul. Jurija Gagarina 5, 59-400 Jawor",
  "Urząd Skarbowy w Jeleniej Górze": "ul. Adama Thebesiusa 1, 58-506 Jelenia Góra",
  "Urząd Skarbowy w Kamiennej Górze": "ul. Papieża Jana Pawła II 18, 58-400 Kamienna Góra",
  "Urząd Skarbowy w Kłodzku": "ul. Stanisławy Walasiewiczówny 1, 57-300 Kłodzko",
  "Urząd Skarbowy w Legnicy": "ul. Wrocławska 37, 59-220 Legnica",
  "Urząd Skarbowy w Lubaniu": "ul. Stara 1, 59-800 Lubań",
  "Urząd Skarbowy w Lubinie": "ul. Marii Skłodowskiej-Curie 94, 59-300 Lubin",
  "Urząd Skarbowy w Lwówku Śląskim": "ul. Budowlanych 1, 59-600 Lwówek Śląski",
  "Urząd Skarbowy w Miliczu": "ul. Składowa 2, 56-300 Milicz",
  "Urząd Skarbowy w Nowej Rudzie": "ul. Kolejowa 23, 57-400 Nowa Ruda",
  "Urząd Skarbowy w Oleśnicy": "ul. Lwowska 34-38, 56-400 Oleśnica",
  "Urząd Skarbowy w Oławie": "ul. Lwowska 1, 55-200 Oława",
  "Urząd Skarbowy w Strzelinie": "ul. Bolka I Świdnickiego 14, 57-100 Strzelin",
  "Urząd Skarbowy w Środzie Śląskiej": "ul. Oławska 5A, 55-300 Środa Śląska",
  "Urząd Skarbowy w Świdnicy": "ul. Marii Skłodowskiej-Curie 1-3, 58-100 Świdnica",
  "Urząd Skarbowy w Trzebnicy": "ul. Prusicka 2, 55-100 Trzebnica",
  "Urząd Skarbowy w Wałbrzychu": "ul. Uczniowska 21, 58-306 Wałbrzych",
  "Urząd Skarbowy w Wołowie": "ul. Tadeusza Kościuszki 17, 56-100 Wołów",
  "Urząd Skarbowy Wrocław-Fabryczna": "ul. Aleksandra Ostrowskiego 5, 53-238 Wrocław",
  "Urząd Skarbowy Wrocław-Krzyki": "ul. Sztabowa 100, 53-310 Wrocław",
  "Urząd Skarbowy Wrocław-Psie Pole": "ul. Trzebnicka 33, 50-231 Wrocław",
  "Urząd Skarbowy Wrocław-Stare Miasto": "ul. Inowrocławska 4, 53-654 Wrocław",
  "Urząd Skarbowy Wrocław-Śródmieście": "ul. marsz. Józefa Piłsudskiego 27-29, 50-044 Wrocław",
  "Pierwszy Urząd Skarbowy we Wrocławiu": "ul. Ks. Czesława Klimasa 34, 50-515 Wrocław",
  "Urząd Skarbowy w Ząbkowicach Śląskich": "ul. Ludwika Waryńskiego 2A, 57-200 Ząbkowice Śląskie",
  "Urząd Skarbowy w Zgorzelcu": "ul. Bohaterów II Armii Wojska Polskiego 8B, 59-900 Zgorzelec",
  "Urząd Skarbowy w Złotoryi": "ul. Stroma 6, 59-500 Złotoryja",
  "Urząd Skarbowy w Górze": "ul. Poznańska 4, 56-200 Góra",
  "Urząd Skarbowy w Polkowicach": "ul. Zachodnia 10, 59-100 Polkowice",
  "Urząd Skarbowy w Aleksandrowie Kujawskim": "ul. Kościelna 18, 87-700 Aleksandrów Kujawski",
  "Urząd Skarbowy w Brodnicy": "ul. Gen. Władysława Sikorskiego 19, 87-300 Brodnica",
  "Pierwszy Urząd Skarbowy w Bydgoszczy": "ul. Fordońska 77, 85-950 Bydgoszcz",
  "Drugi Urząd Skarbowy w Bydgoszczy": "ul. Wojska Polskiego 20B, 85-822 Bydgoszcz",
  "Trzeci Urząd Skarbowy w Bydgoszczy": "ul. Tadeusza Rejtana 5, 85-032 Bydgoszcz",
  "Urząd Skarbowy w Chełmnie": "ul. Grudziądzka 6, 86-200 Chełmno",
  "Urząd Skarbowy w Grudziądzu": "ul. Droga Łąkowa 23, 86-300 Grudziądz",
  "Urząd Skarbowy w Inowrocławiu": "al. Niepodległości 5, 88-100 Inowrocław",
  "Urząd Skarbowy w Lipnie": "ul. Stanisława Staszica 4, 87-600 Lipno",
  "Urząd Skarbowy w Mogilnie": "ul. 900-lecia 20, 88-300 Mogilno",
  "Urząd Skarbowy w Nakle Nad Notecią": "ul. Sądowa 8, 89-100 Nakło nad Notecią",
  "Urząd Skarbowy w Radziejowie": "ul. Rolnicza 6, 88-200 Radziejów",
  "Urząd Skarbowy w Rypinie": "ul. Dojazdowa 10, 87-500 Rypin",
  "Urząd Skarbowy w Świeciu": "ul. 10 lutego 16, 86-100 Świecie",
  "Pierwszy Urząd Skarbowy w Toruniu": "ul. Szosa Chełmińska 34/36, 87-100 Toruń",
  "Drugi Urząd Skarbowy w Toruniu": "ul. Mazowiecka 63, 87-100 Toruń",
  "Urząd Skarbowy w Tucholi": "Pl. Zamkowy 4, 89-500 Tuchola",
  "Urząd Skarbowy w Wąbrzeźnie": "ul. Macieja Rataja 2, 87-200 Wąbrzeźno",
  "Urząd Skarbowy we Włocławku": "ul. Stefana Okrzei 72B, 87-800 Włocławek",
  "Urząd Skarbowy w Żninie": "ul. Klemensa Janickiego 18, 88-400 Żnin",
  "Urząd Skarbowy w Golubiu-Dobrzyniu": "ul. Dr. Jerzego Gerarda Koppa 1A, 87-400 Golub-Dobrzyń",
  "Urząd Skarbowy w Sępólnie Krajeńskim": "ul. Tadeusza Kościuszki 22, 89-400 Sępólno Krajeńskie",
  "Urząd Skarbowy w Białej Podlaskiej": "ul. Prosta 19, 21-500 Biała Podlaska",
  "Urząd Skarbowy w Biłgoraju": "ul. Tadeusza Kościuszki 78, 23-400 Biłgoraj",
  "Urząd Skarbowy w Chełmie": "ul. Obłońska 20A, 22-100 Chełm",
  "Urząd Skarbowy w Hrubieszowie": "ul. 27 Wołyńskiej Dywizji Piechoty AK 11, 22-500 Hrubieszów",
  "Urząd Skarbowy w Janowie Lubelskim": "ul. Wojska Polskiego 32, 23-300 Janów Lubelski",
  "Urząd Skarbowy w Krasnymstawie": "ul. Rzeczna 5, 22-300 Krasnystaw",
  "Urząd Skarbowy w Kraśniku": "ul. Tadeusza Kościuszki 5, 23-200 Kraśnik",
  "Urząd Skarbowy w Lubartowie": "ul. Legionów 55, 21-100 Lubartów",
  "Pierwszy Urząd Skarbowy w Lublinie": "ul. Sądowa 5, 20-027 Lublin",
  "Drugi Urząd Skarbowy w Lublinie": "ul. Tadeusza Szeligowskiego 24, 20-883 Lublin",
  "Trzeci Urząd Skarbowy w Lublinie": "ul. Prezydenta Gabriela Narutowicza 56, 20-016 Lublin",
  "Urząd Skarbowy w Łukowie": "ul. Międzyrzecka 72A, 21-400 Łuków",
  "Urząd Skarbowy w Opolu Lubelskim": "ul. Józefa Piłsudskiego 12, 24-300 Opole Lubelskie",
  "Urząd Skarbowy w Parczewie": "ul. Żabia 2a, 21-200 Parczew",
  "Urząd Skarbowy w Puławach": "ul. Władysława Grabskiego 4, 24-100 Puławy",
  "Urząd Skarbowy w Radzyniu Podlaskim": "ul. Wisznicka 111 E, 21-300 Radzyń Podlaski",
  "Urząd Skarbowy w Tomaszowie Lubelskim": "ul. Rolnicza 17, 22-600 Tomaszów Lubelski",
  "Urząd Skarbowy we Włodawie": "Rynek 9, 22-200 Włodawa",
  "Urząd Skarbowy w Zamościu": "ul. Jana Kilińskiego 82, 22-400 Zamość",
  "Urząd Skarbowy w Łęcznej": "Aleja Jana Pawła II 95, 21-010 Łęczna",
  "Urząd Skarbowy w Rykach": "ul. Leona Wyczółkowskiego 10A, 08-500 Ryki",
  "Urząd Skarbowy w Gorzowie Wielkopolskim": "ul. Kazimierza Jagiellończyka 10, 66-400 Gorzów Wielkopolski",
  "Urząd Skarbowy w Krośnie Odrzańskim": "ul. Słubicka 3, 66-600 Krosno Odrzańskie",
  "Urząd Skarbowy w Międzyrzeczu": "Rynek 3, 66-300 Międzyrzecz",
  "Urząd Skarbowy w Nowej Soli": "ul. Staszica 1, 67-100 Nowa Sól",
  "Urząd Skarbowy w Słubicach": "ul. Wojska Polskiego 155, 69-100 Słubice",
  "Urząd Skarbowy w Świebodzinie": "ul. Sobieskiego 6, 66-200 Świebodzin",
  "Pierwszy Urząd Skarbowy w Zielonej Górze": "ul. Dr. Pieniężnego 24, 65-054 Zielona Góra",
  "Drugi Urząd Skarbowy w Zielonej Górze": "ul. Dr. Pieniężnego 24, 65-054 Zielona Góra",
  "Urząd Skarbowy w Żaganiu": "ul. Skarbowa 26, 68-100 Żagań",
  "Urząd Skarbowy w Żarach": "ul. Osadników Wojskowych 3-4, 68-200 Żary",
  "Urząd Skarbowy w Drezdenku": "ul. Pierwszej Brygady 21, 66-530 Drezdenko",
  "Urząd Skarbowy w Sulęcinie": "ul. Daszyńskiego 47, 69-200 Sulęcin",
  "Urząd Skarbowy we Wschowie": "ul. Zielony Rynek 7, 67-400 Wschowa",
  "Urząd Skarbowy w Bełchatowie": "ul. Józefa Piłsudskiego 18, 97-400 Bełchatów",
  "Urząd Skarbowy w Brzezinach": "ul. Henryka Sienkiewicza 16, 95-060 Brzeziny",
  "Urząd Skarbowy w Głownie": "ul. Ludwika Norblina 2, 95-015 Głowno",
  "Urząd Skarbowy w Kutnie": "ul. Dr. Antoniego Troczewskiego 12, 99-300 Kutno",
  "Urząd Skarbowy w Łasku": "ul. 9 Maja 31, 98-100 Łask",
  "Urząd Skarbowy w Łowiczu": "ul. Józefa Chełmońskiego 2, 99-400 Łowicz",
  "Pierwszy Urząd Skarbowy Łódź-Bałuty": "ul. Zachodnia 47, 91-066 Łódź",
  "Drugi Urząd Skarbowy Łódź-Bałuty": "ul. Św. Teresy od Dzieciątka Jezus 105, 91-222 Łódź",
  "Pierwszy Urząd Skarbowy Łódź-Górna": "ul. Walerego Wróblewskiego 10, 93-578 Łódź",
  "Drugi Urząd Skarbowy Łódź-Górna": "ul. Walerego Wróblewskiego 10A, 93-578 Łódź",
  "Urząd Skarbowy Łódź-Polesie": "ul. 6 Sierpnia 86A, 90-646 Łódź",
  "Urząd Skarbowy Łódź-Śródmieście": "ul. Dowborczyków 9/11, 90-019 Łódź",
  "Urząd Skarbowy Łódź-Widzew": "ul. Papiernicza 7, 92-312 Łódź",
  "Urząd Skarbowy w Opocznie": "ul. Piotrkowska 14, 26-300 Opoczno",
  "Urząd Skarbowy w Pabianicach": "ul. Zamkowa 26, 95-200 Pabianice",
  "Urząd Skarbowy w Piotrkowie Trybunalskim": "ul. Wronia 65, 97-300 Piotrków Trybunalski",
  "Urząd Skarbowy w Poddębicach": "ul. Narutowicza 12, 99-200 Poddębice",
  "Urząd Skarbowy w Radomsku": "ul. Mickiewicza 4, 97-500 Radomsko",
  "Urząd Skarbowy w Rawie Mazowieckiej": "ul. Juliusza Słowackiego 4, 96-200 Rawa Mazowiecka",
  "Urząd Skarbowy w Sieradzu": "ul. Spółdzielcza 3, 98-200 Sieradz",
  "Urząd Skarbowy w Skierniewicach": "ul. Czerwona 22, 96-100 Skierniewice",
  "Urząd Skarbowy w Tomaszowie Mazowieckim": "ul. Mireckiego 37, 97-200 Tomaszów Mazowiecki",
  "Urząd Skarbowy w Wieluniu": "ul. Krakowskie Przedmieście 34, 98-300 Wieluń",
  "Urząd Skarbowy w Zduńskiej Woli": "ul. Zielona 15, 98-220 Zduńska Wola",
  "Urząd Skarbowy w Zgierzu": "ul. ks. Jerzego Popiełuszki 8, 95-100 Zgierz",
  "Urząd Skarbowy w Wieruszowie": "Rynek 12/13, 98-400 Wieruszów",
  "Urząd Skarbowy w Łęczycy": "al. Jana Pawła II 17, 99-100 Łęczyca",
  "Urząd Skarbowy w Pajęcznie": "ul. 1 Maja 9, 98-330 Pajęczno",
  "Urząd Skarbowy w Bochni": "ul. Gołębia 3, 32-700 Bochnia",
  "Urząd Skarbowy w Brzesku": "ul. Królowej Jadwigi 16, 32-800 Brzesko",
  "Urząd Skarbowy w Chrzanowie": "ul. Garncarska 9, 32-500 Chrzanów",
  "Urząd Skarbowy w Dąbrowie Tarnowskiej": "ul. Berka Joselewicza 5, 33-200 Dąbrowa Tarnowska",
  "Urząd Skarbowy w Gorlicach": "ul. Bardiowska 9, 38-300 Gorlice",
  "Pierwszy Urząd Skarbowy w Krakowie": "ul. Rzemieślnicza 20, 30-363 Kraków",
  "Urząd Skarbowy Kraków-Krowodrza": "ul. Władysława Łokietka 20, 30-016 Kraków",
  "Urząd Skarbowy Kraków-Nowa Huta": "os. Bohaterów Września 80, 31-621 Kraków",
  "Urząd Skarbowy Kraków-Podgórze": "ul. Wadowicka 10, 30-415 Kraków",
  "Urząd Skarbowy Kraków-Prądnik": "ul. Janogórska 11, 31-358 Kraków",
  "Urząd Skarbowy Kraków-Stare Miasto": "ul. Grodzka 65, 31-001 Kraków",
  "Urząd Skarbowy Kraków-Śródmieście": "ul. Janogórska 11, 31-358 Kraków",
  "Urząd Skarbowy w Limanowej": "ul. Matki Boskiej Bolesnej 9, 34-600 Limanowa",
  "Urząd Skarbowy w Miechowie": "ul. Stanisławy Daneckiej 1, 32-200 Miechów",
  "Urząd Skarbowy w Myślenicach": "ul. Hipolita Cegielskiego 2, 32-400 Myślenice",
  "Urząd Skarbowy w Nowym Sączu": "ul. Władysława Barbackiego 10, 33-300 Nowy Sącz",
  "Urząd Skarbowy w Nowym Targu": "Parkowa 13, 34-400 Nowy Targ",
  "Urząd Skarbowy w Olkuszu": "ul. Budowlanych 2, 32-300 Olkusz",
  "Urząd Skarbowy w Oświęcimiu": "ul. Plebańska 2, 32-600 Oświęcim",
  "Urząd Skarbowy w Proszowicach": "ul. Mikołaja Reja 1, 32-100 Proszowice",
  "Urząd Skarbowy w Suchej Beskidzkiej": "ul. Adama Mickiewicza 36, 34-200 Sucha Beskidzka",
  "Pierwszy Urząd Skarbowy w Tarnowie": "ul. Lwowska 72-96A, 33-100 Tarnów",
  "Drugi Urząd Skarbowy w Tarnowie": "Al.Solidarności 5-9B, 33-100 Tarnów",
  "Urząd Skarbowy w Wadowicach": "ul. Legionów 22, 34-100 Wadowice",
  "Urząd Skarbowy w Wieliczce": "ul. Zamkowa 2, 32-020 Wieliczka",
  "Urząd Skarbowy w Zakopanem": "ul. Szymony 14, 34-500 Zakopane",
  "Drugi Urząd Skarbowy Kraków": "ul. Jasnogórska 11, 31-358 Kraków",
  "Urząd Skarbowy w Białobrzegach": "ul. Władysława Stanisława Reymonta 46, 26-800 Białobrzegi",
  "Urząd Skarbowy w Ciechanowie": "ul. Warszawska 58, 06-400 Ciechanów",
  "Urząd Skarbowy w Garwolinie": "ul. Senatorska 30, 08-400 Garwolin",
  "Urząd Skarbowy w Gostyninie": "ul. Płocka 10, 09-500 Gostynin",
  "Urząd Skarbowy w Grodzisku Mazowieckim": "ul. Daleka 22, 05-825 Grodzisk Mazowiecki",
  "Urząd Skarbowy w Grójcu": "ul. Ks. Piotra Skargi 35, 05-600 Grójec",
  "Urząd Skarbowy w Kozienicach": "Parkowa 5, 26-900 Kozienice",
  "Urząd Skarbowy w Legionowie": "ul. Marszałka Józefa Piłsudskiego 43C, 05-120 Legionowo",
  "Urząd Skarbowy w Łosicach": "ul. 11 Listopada 1, 08-200 Łosice",
  "Urząd Skarbowy w Makowie Mazowieckim": "ul. Kopernika 6C, 06-200 Maków Mazowiecki",
  "Urząd Skarbowy w Mińsku Mazowieckim": "ul. Szczecińska 2, 05-300 Mińsk Mazowiecki",
  "Urząd Skarbowy w Mławie": "ul. Gabriela Narutowicza 19/7, 06-500 Mława",
  "Urząd Skarbowy w Nowym Dworze Mazowieckim": "ul. Legionów 7, 05-100 Nowy Dwór Mazowiecki",
  "Urząd Skarbowy w Ostrołęce": "ul. Przechodnia 6, 07-410 Ostrołęka",
  "Urząd Skarbowy w Ostrowi Mazowieckiej": "ul. Stanisława Duboisa 1, 07-300 Ostrów Mazowiecka",
  "Urząd Skarbowy w Otwocku": "ul. Jana Matejki 4, 05-400 Otwock",
  "Urząd Skarbowy w Piasecznie": "ul. Energetyczna 5, 05-500 Piaseczno",
  "Urząd Skarbowy w Płocku": "ul. 1 Maja 10, 09-402 Płock",
  "Urząd Skarbowy w Płońsku": "ul. Spółdzielcza 2, 09-100 Płońsk",
  "Urząd Skarbowy w Pruszkowie": "ul. Stanisława Staszica 1, 05-800 Pruszków",
  "Urząd Skarbowy w Przasnyszu": "ul. Świerkowa 3, 06-300 Przasnysz",
  "Urząd Skarbowy w Pułtusku": "ul. Żwirki i Wigury 7, 06-100 Pułtusk",
  "Pierwszy Urząd Skarbowy w Radomiu": "ul. Stanisława Zbrowskiego 106, 26-615 Radom",
  "Drugi Urząd Skarbowy w Radomiu": "ul. Toruńska 3, 26-600 Radom",
  "Urząd Skarbowy w Siedlcach": "ul. Bp. Ignacego Świrskiego 45, 08-110 Siedlce",
  "Urząd Skarbowy w Sierpcu": "ul. Piastowska 48, 09-200 Sierpc",
  "Urząd Skarbowy w Sochaczewie": "ul. Władysława Grabskiego 4, 96-500 Sochaczew",
  "Urząd Skarbowy w Sokołowie Podlaskim": "ul. Węgrowska 5, 08-300 Sokołów Podlaski",
  "Urząd Skarbowy w Szydłowcu": "ul. Widok 6, 26-500 Szydłowiec",
  "Urząd Skarbowy Warszawa-Bemowo": "ul. Białobrzeska 53A, 02-325 Warszawa",
  "Urząd Skarbowy Warszawa-Bielany": "ul. Skalbmierska 5, 01-844 Warszawa",
  "Urząd Skarbowy Warszawa-Mokotów": "ul. Fabryki \"Tewa\" 3, 02-676 Warszawa",
  "Urząd Skarbowy Warszawa-Praga": "ul. Jagiellońska 15, 03-719 Warszawa",
  "Pierwszy Urząd Skarbowy Warszawa-Śródmieście": "ul. Williama Lindleya 14, 02-013 Warszawa",
  "Drugi Urząd Skarbowy Warszawa-Śródmieście": "ul. Jagiellońska 15, 03-719 Warszawa",
  "Urząd Skarbowy Warszawa-Targówek": "ul. Dąbrowszczaków 14, 03-484 Warszawa",
  "Urząd Skarbowy Warszawa-Ursynów": "ul. Wynalazek 3, 02-677 Warszawa",
  "Urząd Skarbowy Warszawa-Wawer": "ul. Ludwika Mycielskiego 21, 04-379 Warszawa",
  "Urząd Skarbowy Warszawa-Wola": "ul. Powstańców Śląskich 2D, 01-381 Warszawa",
  "Urząd Skarbowy w Węgrowie": "ul. Tadeusza Kościuszki 10, 07-100 Węgrów",
  "Urząd Skarbowy w Wołominie": "ul. Przejazd 2, 05-200 Wołomin",
  "Urząd Skarbowy w Wyszkowie": "ul. Gen. Józefa Sowińskiego 82, 07-200 Wyszków",
  "Urząd Skarbowy w Zwoleniu": "ul. Wojska Polskiego 39, 26-700 Zwoleń",
  "Urząd Skarbowy w Żurominie": "Plac Józefa Piłsudskiego 4, 09-300 Żuromin",
  "Urząd Skarbowy w Żyrardowie": "ul. 1 Maja 49A, 96-300 Żyrardów",
  "Urząd Skarbowy w Lipsku": "ul. Solecka 88, 27-300 Lipsko",
  "Urząd Skarbowy w Przysusze": "ul. Szkolna 7, 26-400 Przysucha",
  "Trzeci Urząd Skarbowy Warszawa-Śródmieście": "ul. Williama Lindleya 14, 02-013 Warszawa",
  "Urząd Skarbowy w Brzegu": "ul. Składowa 2, 49-305 Brzeg",
  "Urząd Skarbowy w Głubczycach": "ul. Fabryczna 2, 48-100 Głubczyce",
  "Urząd Skarbowy w Kędzierzynie-Koźlu": "ul. Piotra Skargi 19, 47-224 Kędzierzyn-Koźle",
  "Urząd Skarbowy w Kluczborku": "ul. Sienkiewicza 22A, 46-200 Kluczbork",
  "Urząd Skarbowy w Namysłowie": "ul. Marii Skłodowskiej-Curie 12, 46-100 Namysłów",
  "Urząd Skarbowy w Nysie": "ul. Bolesława Krzywoustego 23, 48-300 Nysa",
  "Urząd Skarbowy w Oleśnie": "ul. Jana Pieloka 21, 46-300 Olesno",
  "Pierwszy Urząd Skarbowy w Opolu": "ul. Tadeusza Rejtana 3B, 45-331 Opole",
  "Drugi Urząd Skarbowy w Opolu": "ul. płk. Witolda Pileckiego 2, 45-331 Opole",
  "Urząd Skarbowy w Prudniku": "ul. Mikołaja Kopernika 1A, 48-200 Prudnik",
  "Urząd Skarbowy w Strzelcach Opolskich": "ul. Opolska 13, 47-100 Strzelce Opolskie",
  "Urząd Skarbowy w Krapkowicach": "ul. Opolska 96A, 47-300 Krapkowice",
  "Urząd Skarbowy w Brzozowie": "ul. Kazimierzowska 1, 36-200 Brzozów",
  "Urząd Skarbowy w Dębicy": "ul. Kolejowa 21, 39-200 Dębica",
  "Urząd Skarbowy w Jarosławiu": "ul. Przemysłowa 2A, 37-500 Jarosław",
  "Urząd Skarbowy w Jaśle": "ul. Stanisława Staszica 3, 38-200 Jasło",
  "Urząd Skarbowy w Kolbuszowej": "ul. Tadeusza Kościuszki 20, 36-100 Kolbuszowa",
  "Urząd Skarbowy w Krośnie": "ul. Składowa 5, 38-400 Krosno",
  "Urząd Skarbowy w Lesku": "Rynek 1, 38-600 Lesko",
  "Urząd Skarbowy w Leżajsku": "Plac Targowy 3, 37-300 Leżajsk",
  "Urząd Skarbowy w Lubaczowie": "ul. Jana III Sobieskiego 6, 37-600 Lubaczów",
  "Urząd Skarbowy w Łańcucie": "ul. Józefa Piłsudskiego 11, 37-100 Łańcut",
  "Urząd Skarbowy w Mielcu": "ul. Żeromskiego 13, 39-300 Mielec",
  "Urząd Skarbowy w Przemyślu": "ul. Lwowska 9A, 37-700 Przemyśl",
  "Urząd Skarbowy w Przeworsku": "ul. Tysiąclecia 1, 37-200 Przeworsk",
  "Urząd Skarbowy w Ropczycach": "ul. Świętej Barbary 12, 39-100 Ropczyce",
  "Pierwszy Urząd Skarbowy w Rzeszowie": "ul. Podwisłocze 42, 35-309 Rzeszów",
  "Urząd Skarbowy w Sanoku": "ul. Kiczury 16, 38-500 Sanok",
  "Urząd Skarbowy w Stalowej Woli": "ul. Metalowców 6, 37-450 Stalowa Wola",
  "Urząd Skarbowy w Strzyżowie": "ul. Daszyńskiego 6, 38-100 Strzyżów",
  "Urząd Skarbowy w Tarnobrzegu": "ul. Stanisława Wyspiańskiego 12, 39-400 Tarnobrzeg",
  "Urząd Skarbowy w Ustrzykach Dolnych": "ul. Mikołaja Kopernika 1, 38-700 Ustrzyki Dolne",
  "Drugi Urząd Skarbowy w Rzeszowie": "ul. Lucjana Siemieńskiego 18, 35-234 Rzeszów",
  "Urząd Skarbowy w Nisku": "ul. 3 Maja 32B, 37-400 Nisko",
  "Urząd Skarbowy w Augustowie": "ul. Żabia 7, 16-300 Augustów",
  "Pierwszy Urząd Skarbowy w Białymstoku": "ul. Świętojańska 13, 15-219 Białystok",
  "Drugi Urząd Skarbowy w Białymstoku": "ul. Plażowa 17, 15-502 Białystok",
  "Urząd Skarbowy w Bielsku Podlaskim": "ul. Adama Mickiewicza 33, 17-100 Bielsk Podlaski",
  "Urząd Skarbowy w Grajewie": "ul. Elewatorska 8, 19-200 Grajewo",
  "Urząd Skarbowy w Kolnie": "ul. Wojska Polskiego 20, 18-500 Kolno",
  "Urząd Skarbowy w Łomży": "ul. Polowa 47, 18-400 Łomża",
  "Urząd Skarbowy w Mońkach": "ul. Ełcka 41A, 19-100 Mońki",
  "Urząd Skarbowy w Siemiatyczach": "ul. Pałacowa 18, 17-300 Siemiatycze",
  "Urząd Skarbowy w Sokółce": "ul. Białostocka 47, 16-100 Sokółka",
  "Urząd Skarbowy w Suwałkach": "ul. 1 Maja 2A, 16-400 Suwałki",
  "Urząd Skarbowy w Wysokiem Mazowieckiem": "ul. Ludowa 21, 18-200 Wysokie Mazowieckie",
  "Urząd Skarbowy w Zambrowie": "ul. Jantarowa 16, 18-300 Zambrów",
  "Urząd Skarbowy w Hajnówce": "ul. 3 Maja 34, 17-200 Hajnówka",
  "Urząd Skarbowy w Bytowie": "ul. 1 Maja 16, 77-100 Bytów",
  "Urząd Skarbowy w Chojnicach": "ul. Młyńska 22, 89-600 Chojnice",
  "Urząd Skarbowy w Człuchowie": "ul. Jerzego z Dąbrowy 5E, 77-300 Człuchów",
  "Pierwszy Urząd Skarbowy w Gdańsku": "ul. Rzeźnicka 54/56, 80-822 Gdańsk",
  "Drugi Urząd Skarbowy w Gdańsku": "ul. Kołobrzeska 43, 80-391 Gdańsk",
  "Trzeci Urząd Skarbowy w Gdańsku": "ul. Chłopska 3, 80-362 Gdańsk",
  "Pierwszy Urząd Skarbowy w Gdyni": "ul. Władysława IV 2/4, 81-353 Gdynia",
  "Drugi Urząd Skarbowy w Gdyni": "ul. Hutnicza 25, 81-061 Gdynia",
  "Urząd Skarbowy w Kartuzach": "ul. Kościerska 13, 83-300 Kartuzy",
  "Urząd Skarbowy w Kościerzynie": "ul. Staszica 6, 83-400 Kościerzyna",
  "Urząd Skarbowy w Kwidzynie": "ul. 3 Maja 6, 82-500 Kwidzyn",
  "Urząd Skarbowy w Lęborku": "ul. Słupska 23, 84-300 Lębork",
  "Urząd Skarbowy w Malborku": "ul. Mikołaja Kopernika 10, 82-200 Malbork",
  "Urząd Skarbowy w Pucku": "ul. Kmdr. E. Szystowskiego 18, 84-100 Puck",
  "Urząd Skarbowy w Słupsku": "ul. Szczecińska 59, 76-200 Słupsk",
  "Urząd Skarbowy w Sopocie": "ul. 23 Marca 9/11, 81-808 Sopot",
  "Urząd Skarbowy w Starogardzie Gdańskim": "ul. Lubichowska 4, 83-200 Starogard Gdański",
  "Urząd Skarbowy w Tczewie": "ul. Gdańska 33, 83-110 Tczew",
  "Urząd Skarbowy w Wejherowie": "ul. Jana III Sobieskiego 346, 84-200 Wejherowo",
  "Urząd Skarbowy w Pruszczu Gdańskim": "ul. Ignacego Łukasiewicza 2, 83-000 Pruszcz Gdański",
  "Urząd Skarbowy w Będzinie": "ul. Józefa Retingera 1, 42-500 Będzin",
  "Pierwszy Urząd Skarbowy w Bielsku-Białej": "ul. Teodora Sixta 17, 43-300 Bielsko-Biała",
  "Drugi Urząd Skarbowy w Bielsku-Białej": "ul. Gen. Stanisława Maczka 73, 43-300 Bielsko-Biała",
  "Urząd Skarbowy w Bytomiu": "ul. Wrocławska 92, 41-902 Bytom",
  "Urząd Skarbowy w Chorzowie": "ul. Armii Krajowej 5, 41-506 Chorzów",
  "Urząd Skarbowy w Cieszynie": "ul. Ignacego Kraszewskiego 4, 43-400 Cieszyn",
  "Urząd Skarbowy w Czechowicach-Dziedzicach": "ul. Nad Białką 1A, 43-502 Czechowice-Dziedzice",
  "Pierwszy Urząd Skarbowy w Częstochowie": "ul. Filomatów 18/20, 42-217 Częstochowa",
  "Drugi Urząd Skarbowy w Częstochowie": "ul. Tkacka 3, 42-200 Częstochowa",
  "Urząd Skarbowy w Dąbrowie Górniczej": "ul. Zygmunta Krasińskiego 33A, 41-300 Dąbrowa Górnicza",
  "Pierwszy Urząd Skarbowy w Gliwicach": "ul. Góry Chełmskiej 15, 44-100 Gliwice",
  "Drugi Urząd Skarbowy w Gliwicach": "ul. Młodego Hutnika 2, 44-100 Gliwice",
  "Urząd Skarbowy w Jastrzębiu-Zdroju": "ul. 11 Listopada 13, 44-335 Jastrzębie-Zdrój",
  "Urząd Skarbowy w Jaworznie": "ul. Grunwaldzka 274A, 43-600 Jaworzno",
  "Pierwszy Urząd Skarbowy w Katowicach": "ul. Żwirki i Wigury 17, 40-063 Katowice",
  "Drugi Urząd Skarbowy w Katowicach": "ul. Ignacego Paderewskiego 32B, 40-282 Katowice",
  "Urząd Skarbowy w Kłobucku": "Rynek im. Jana Pawła II 13, 42-100 Kłobuck",
  "Urząd Skarbowy w Lublińcu": "ul. Ignacego Paderewskiego 7B, 42-700 Lubliniec",
  "Urząd Skarbowy w Mikołowie": "ul. prof. Maksymiliana Hubera 4, 43-190 Mikołów",
  "Urząd Skarbowy w Mysłowicach": "ul. Adama Mickiewicza 4, 41-400 Mysłowice",
  "Urząd Skarbowy w Myszkowie": "ul. Rozwojowa 2, 42-300 Myszków",
  "Urząd Skarbowy w Piekarach Śląskich": "ul. Bytomska 92, 41-940 Piekary Śląskie",
  "Urząd Skarbowy w Pszczynie": "ul. 3 Maja 4, 43-200 Pszczyna",
  "Urząd Skarbowy w Raciborzu": "ul. Michała Drzymały 32, 47-400 Racibórz",
  "Urząd Skarbowy w Rudzie Śląskiej": "ul. Kokotek 6, 41-700 Ruda Śląska",
  "Urząd Skarbowy w Rybniku": "Pl. Armii Krajowej 3, 44-200 Rybnik",
  "Urząd Skarbowy w Siemianowicach Śląskich": "ul. Śląska 84, 41-100 Siemianowice Śląskie",
  "Urząd Skarbowy w Sosnowcu": "ul. 3 Maja 20, 41-200 Sosnowiec",
  "Urząd Skarbowy w Tarnowskich Górach": "ul. Opolska 23, 42-600 Tarnowskie Góry",
  "Urząd Skarbowy w Tychach": "Al. Niepodległości 60, 43-100 Tychy",
  "Urząd Skarbowy w Wodzisławiu Śląskim": "ul. Bartosza Głowackiego 4, 44-300 Wodzisław Śląski",
  "Urząd Skarbowy w Zabrzu": "ul. Bytomska 2, 41-800 Zabrze",
  "Urząd Skarbowy w Zawierciu": "ul. Leśna 8, 42-400 Zawiercie",
  "Urząd Skarbowy w Żorach": "ul. Wodzisławska 1, 44-240 Żory",
  "Urząd Skarbowy w Żywcu": "ul. Zygmunta Krasińskiego 11, 34-300 Żywiec",
  "Urząd Skarbowy w Busku-Zdroju": "Parkowa 17, 28-100 Busko-Zdrój",
  "Urząd Skarbowy w Jędrzejowie": "ul. 11 Listopada 33, 28-300 Jędrzejów",
  "Pierwszy Urząd Skarbowy w Kielcach": "ul. Wróbla 17, 25-661 Kielce",
  "Drugi Urząd Skarbowy w Kielcach": "ul. Częstochowska 20, 25-647 Kielce",
  "Urząd Skarbowy w Końskich": "ul. Marszałka Piłsudskiego 156B, 26-200 Końskie",
  "Urząd Skarbowy w Opatowie": "ul. Jana Kilińskiego 9, 27-500 Opatów",
  "Urząd Skarbowy w Ostrowcu Świętokrzyskim": "ul. Polna 11, 27-400 Ostrowiec Świętokrzyski",
  "Urząd Skarbowy w Pińczowie": "ul. Grodziskowa 1, 28-400 Pińczów",
  "Urząd Skarbowy w Sandomierzu": "ul. Żydowska 1, 27-600 Sandomierz",
  "Urząd Skarbowy w Skarżysku-Kamiennej": "ul. 1 Maja 56, 26-110 Skarżysko-Kamienna",
  "Urząd Skarbowy w Starachowicach": "ul. Składowa 33, 27-200 Starachowice",
  "Urząd Skarbowy w Staszowie": "ul. Oględowska 12, 28-200 Staszów",
  "Urząd Skarbowy w Kazimierzy Wielkiej": "ul. Tadeusza Kościuszki 16, 28-500 Kazimierza Wielka",
  "Urząd Skarbowy we Włoszczowie": "ul. Wiśniowa 10, 29-100 Włoszczowa",
  "Urząd Skarbowy w Bartoszycach": "ul. Boh. Warszawy 5, 11-200 Bartoszyce",
  "Urząd Skarbowy w Braniewie": "ul. Jana Matejki 6, 14-500 Braniewo",
  "Urząd Skarbowy w Działdowie": "ul. Marii Skłodowskiej-Curie 35A, 13-200 Działdowo",
  "Urząd Skarbowy w Elblągu": "ul. Adama Mickiewicza 43, 82-300 Elbląg",
  "Urząd Skarbowy w Ełku": "ul. Wojska Polskiego 67, 19-300 Ełk",
  "Urząd Skarbowy w Giżycku": "ul. Tadeusza Kościuszki 15, 11-500 Giżycko",
  "Urząd Skarbowy w Iławie": "ul. Wojska Polskiego 26, 14-200 Iława",
  "Urząd Skarbowy w Kętrzynie": "ul. Powstańców Warszawy 13, 11-400 Kętrzyn",
  "Urząd Skarbowy w Nidzicy": "ul. Żeromskiego 11, 13-100 Nidzica",
  "Urząd Skarbowy w Nowym Mieście Lubawskim": "ul. Działyńskich 3, 13-300 Nowe Miasto Lubawskie",
  "Urząd Skarbowy w Olecku": "ul. Wojska Polskiego 7, 19-400 Olecko",
  "Urząd Skarbowy w Olsztynie": "Aleja Marszałka Józefa Piłsudskiego 59, 10-950 Olsztyn",
  "Urząd Skarbowy w Ostródzie": "ul. Olsztyńska 5B, 14-100 Ostróda",
  "Urząd Skarbowy w Piszu": "ul. Okopowa 2, 12-200 Pisz",
  "Urząd Skarbowy w Szczytnie": "ul. Warszawska 5, 12-100 Szczytno",
  "Urząd Skarbowy w Czarnkowie": "ul. Wodna 8, 64-700 Czarnków",
  "Urząd Skarbowy w Gnieźnie": "ul. Spichrzowa 4, 62-200 Gniezno",
  "Urząd Skarbowy w Gostyniu": "ul. Lipowa 2, 63-800 Gostyń",
  "Urząd Skarbowy w Grodzisku Wielkopolskim": "ul. Chopina 7, 62-065 Grodzisk Wielkopolski",
  "Urząd Skarbowy w Jarocinie": "ul. Tadeusza Kościuszki 21, 63-200 Jarocin",
  "Pierwszy Urząd Skarbowy w Kaliszu": "ul. Wrocławska 12, 62-800 Kalisz",
  "Drugi Urząd Skarbowy w Kaliszu": "ul. Fabryczna 1a, 62-800 Kalisz",
  "Urząd Skarbowy w Kępnie": "Rynek 4, 63-600 Kępno",
  "Urząd Skarbowy w Kole": "ul. Bolesława Prusa 10, 62-600 Koło",
  "Urząd Skarbowy w Koninie": "ul. Zakładowa 7A, 62-510 Konin",
  "Urząd Skarbowy w Kościanie": "ul. Młyńska 5, 64-000 Kościan",
  "Urząd Skarbowy w Krotoszynie": "ul. Polna 32, 63-700 Krotoszyn",
  "Urząd Skarbowy w Lesznie": "ul. Adama Mickiewicza 7, 64-100 Leszno",
  "Urząd Skarbowy w Międzychodzie": "ul. Marszałka Piłsudskiego 2, 64-400 Międzychód",
  "Urząd Skarbowy w Nowym Tomyślu": "ul. Kolejowa 38, 64-300 Nowy Tomyśl",
  "Urząd Skarbowy w Ostrowie Wielkopolskim": "ul. Chłapowskiego 45, 63-400 Ostrów Wielkopolski",
  "Urząd Skarbowy w Ostrzeszowie": "ul. Władysława Grabskiego 1, 63-500 Ostrzeszów",
  "Urząd Skarbowy w Pile": "ul. Kossaka 106, 64-920 Piła",
  "Urząd Skarbowy Poznań-Grunwald": "ul. Mariana Smoluchowskiego 1, 60-179 Poznań",
  "Urząd Skarbowy Poznań-Jeżyce": "ul. Strzelecka 2/6, 61-845 Poznań",
  "Urząd Skarbowy Poznań-Nowe Miasto": "ul. Dezyderego Chłapowskiego 17/18, 60-965 Poznań",
  "Pierwszy Urząd Skarbowy w Poznaniu": "ul. Dolna Wilda 80, 61-501 Poznań",
  "Urząd Skarbowy Poznań-Winogrady": "ul. Zygmunta Wojciechowskiego 3/5, 60-685 Poznań",
  "Urząd Skarbowy Poznań-Wilda": "ul. Dolna Wilda 80B, 61-501 Poznań",
  "Urząd Skarbowy w Rawiczu": "ul. Stanisława Staszica 4, 63-900 Rawicz",
  "Urząd Skarbowy w Słupcy": "ul. Wspólna 1, 62-400 Słupca",
  "Urząd Skarbowy w Szamotułach": "ul. Bolesława Chrobrego 17A, 64-500 Szamotuły",
  "Urząd Skarbowy w Śremie": "ul. Wojska Polskiego 12, 63-100 Śrem",
  "Urząd Skarbowy w Środzie Wielkopolskiej": "ul. Harcerska 2, 63-000 Środa Wielkopolska",
  "Urząd Skarbowy w Turku": "ul. Konińska 1, 62-700 Turek",
  "Urząd Skarbowy w Wągrowcu": "ul. Kościuszki 19A, 62-100 Wągrowiec",
  "Urząd Skarbowy w Wolsztynie": "ul. Dworcowa 15, 64-200 Wolsztyn",
  "Urząd Skarbowy we Wrześni": "ul. Warszawska 26, 62-300 Września",
  "Urząd Skarbowy w Złotowie": "Al. Piasta 25, 77-400 Złotów",
  "Urząd Skarbowy w Chodzieży": "ul. Ofiar Gór Morzewskich 1, 64-800 Chodzież",
  "Urząd Skarbowy w Obornikach": "Rynek 4, 64-600 Oborniki",
  "Urząd Skarbowy w Pleszewie": "ul. M. Bogusza 6, 63-300 Pleszew",
  "Urząd Skarbowy w Białogardzie": "ul. Mickiewicza 3, 78-200 Białogard",
  "Urząd Skarbowy w Choszcznie": "ul. Lipcowa 16, 73-200 Choszczno",
  "Urząd Skarbowy w Drawsku Pomorskim": "ul. Józefa Piłsudskiego 35-37, 78-500 Drawsko Pomorskie",
  "Urząd Skarbowy w Goleniowie": "Plac Lotników 1, 72-100 Goleniów",
  "Urząd Skarbowy w Gryficach": "ul. Niepodległości 54A, 72-300 Gryfice",
  "Urząd Skarbowy w Gryfinie": "ul. Szczecińska 24, 74-100 Gryfino",
  "Urząd Skarbowy w Kamieniu Pomorskim": "ul. Mieszka I 5B, 72-400 Kamień Pomorski",
  "Urząd Skarbowy w Kołobrzegu": "ul. Armii Krajowej 2, 78-100 Kołobrzeg",
  "Pierwszy Urząd Skarbowy w Koszalinie": "ul. Przemysłowa 3, 75-216 Koszalin",
  "Drugi Urząd Skarbowy w Koszalinie": "ul. Stanisława Moniuszki 15, 75-549 Koszalin",
  "Urząd Skarbowy w Myśliborzu": "ul. Witolda Pileckiego 18, 74-300 Myślibórz",
  "Urząd Skarbowy w Pyrzycach": "ul. 1 Maja 16, 74-200 Pyrzyce",
  "Urząd Skarbowy w Stargardzie Szczecińskim": "ul. Towarowa 15, 73-110 Stargard",
  "Pierwszy Urząd Skarbowy w Szczecinie": "ul. Michała Drzymały 5, 70-217 Szczecin",
  "Drugi Urząd Skarbowy w Szczecinie": "ul. Wacława Felczaka 19, 71-417 Szczecin",
  "Trzeci Urząd Skarbowy w Szczecinie": "ul. Lucjana Rydla 65, 70-783 Szczecin",
  "Urząd Skarbowy w Szczecinku": "ul. Mickiewicza 13/14, 78-400 Szczecinek",
  "Urząd Skarbowy w Świnoujściu": "ul. Kazimierza Pułaskiego 7, 72-600 Świnoujście",
  "Urząd Skarbowy w Wałczu": "ul. T. Kościuszki 4, 78-600 Wałcz",
};

export function taxOfficeAddressOf(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = name.trim();
  return TAX_OFFICE_ADDRESSES[key] ?? null;
}
