// Офіційний перелік усіх urzędów skarbowych (400) — джерело: XSD-словник
// e-Deklaracje (http://www.e-deklaracje.mf.gov.pl/Repozytorium/Slowniki/KodyUrzedowSkarbowych_v3-0.xsd),
// звірено 31.08.2026. Лише назви (без кодів — нам потрібен текст для анкети/умови,
// не сам код). Для автопідбору за адресою офіційного безкоштовного джерела немає
// (перевірено) — це довідник для випадаючого списку з пошуком, значення вводить
// сам працівник/офіс.
export const TAX_OFFICES: string[] = [
  "Urząd Skarbowy w Bolesławcu",
  "Urząd Skarbowy w Bystrzycy Kłodzkiej",
  "Urząd Skarbowy w Dzierżoniowie",
  "Urząd Skarbowy w Głogowie",
  "Urząd Skarbowy w Jaworze",
  "Urząd Skarbowy w Jeleniej Górze",
  "Urząd Skarbowy w Kamiennej Górze",
  "Urząd Skarbowy w Kłodzku",
  "Urząd Skarbowy w Legnicy",
  "Urząd Skarbowy w Lubaniu",
  "Urząd Skarbowy w Lubinie",
  "Urząd Skarbowy w Lwówku Śląskim",
  "Urząd Skarbowy w Miliczu",
  "Urząd Skarbowy w Nowej Rudzie",
  "Urząd Skarbowy w Oleśnicy",
  "Urząd Skarbowy w Oławie",
  "Urząd Skarbowy w Strzelinie",
  "Urząd Skarbowy w Środzie Śląskiej",
  "Urząd Skarbowy w Świdnicy",
  "Urząd Skarbowy w Trzebnicy",
  "Urząd Skarbowy w Wałbrzychu",
  "Urząd Skarbowy w Wołowie",
  "Urząd Skarbowy Wrocław-Fabryczna",
  "Urząd Skarbowy Wrocław-Krzyki",
  "Urząd Skarbowy Wrocław-Psie Pole",
  "Urząd Skarbowy Wrocław-Stare Miasto",
  "Urząd Skarbowy Wrocław-Śródmieście",
  "Pierwszy Urząd Skarbowy we Wrocławiu",
  "Urząd Skarbowy w Ząbkowicach Śląskich",
  "Urząd Skarbowy w Zgorzelcu",
  "Urząd Skarbowy w Złotoryi",
  "Urząd Skarbowy w Górze",
  "Urząd Skarbowy w Polkowicach",
  "Dolnośląski Urząd Skarbowy we Wrocławiu",
  "Urząd Skarbowy w Aleksandrowie Kujawskim",
  "Urząd Skarbowy w Brodnicy",
  "Pierwszy Urząd Skarbowy w Bydgoszczy",
  "Drugi Urząd Skarbowy w Bydgoszczy",
  "Trzeci Urząd Skarbowy w Bydgoszczy",
  "Urząd Skarbowy w Chełmnie",
  "Urząd Skarbowy w Grudziądzu",
  "Urząd Skarbowy w Inowrocławiu",
  "Urząd Skarbowy w Lipnie",
  "Urząd Skarbowy w Mogilnie",
  "Urząd Skarbowy w Nakle Nad Notecią",
  "Urząd Skarbowy w Radziejowie",
  "Urząd Skarbowy w Rypinie",
  "Urząd Skarbowy w Świeciu",
  "Pierwszy Urząd Skarbowy w Toruniu",
  "Drugi Urząd Skarbowy w Toruniu",
  "Urząd Skarbowy w Tucholi",
  "Urząd Skarbowy w Wąbrzeźnie",
  "Urząd Skarbowy we Włocławku",
  "Urząd Skarbowy w Żninie",
  "Urząd Skarbowy w Golubiu-Dobrzyniu",
  "Urząd Skarbowy w Sępólnie Krajeńskim",
  "Kujawsko-Pomorski Urząd Skarbowy w Bydgoszczy",
  "Urząd Skarbowy w Białej Podlaskiej",
  "Urząd Skarbowy w Biłgoraju",
  "Urząd Skarbowy w Chełmie",
  "Urząd Skarbowy w Hrubieszowie",
  "Urząd Skarbowy w Janowie Lubelskim",
  "Urząd Skarbowy w Krasnymstawie",
  "Urząd Skarbowy w Kraśniku",
  "Urząd Skarbowy w Lubartowie",
  "Pierwszy Urząd Skarbowy w Lublinie",
  "Drugi Urząd Skarbowy w Lublinie",
  "Trzeci Urząd Skarbowy w Lublinie",
  "Urząd Skarbowy w Łukowie",
  "Urząd Skarbowy w Opolu Lubelskim",
  "Urząd Skarbowy w Parczewie",
  "Urząd Skarbowy w Puławach",
  "Urząd Skarbowy w Radzyniu Podlaskim",
  "Urząd Skarbowy w Tomaszowie Lubelskim",
  "Urząd Skarbowy we Włodawie",
  "Urząd Skarbowy w Zamościu",
  "Urząd Skarbowy w Łęcznej",
  "Urząd Skarbowy w Rykach",
  "Lubelski Urząd Skarbowy w Lublinie",
  "Urząd Skarbowy w Gorzowie Wielkopolskim",
  "Urząd Skarbowy w Krośnie Odrzańskim",
  "Urząd Skarbowy w Międzyrzeczu",
  "Urząd Skarbowy w Nowej Soli",
  "Urząd Skarbowy w Słubicach",
  "Urząd Skarbowy w Świebodzinie",
  "Pierwszy Urząd Skarbowy w Zielonej Górze",
  "Drugi Urząd Skarbowy w Zielonej Górze",
  "Urząd Skarbowy w Żaganiu",
  "Urząd Skarbowy w Żarach",
  "Urząd Skarbowy w Drezdenku",
  "Urząd Skarbowy w Sulęcinie",
  "Urząd Skarbowy we Wschowie",
  "Lubuski Urząd Skarbowy w Zielonej Górze",
  "Urząd Skarbowy w Bełchatowie",
  "Urząd Skarbowy w Brzezinach",
  "Urząd Skarbowy w Głownie",
  "Urząd Skarbowy w Kutnie",
  "Urząd Skarbowy w Łasku",
  "Urząd Skarbowy w Łowiczu",
  "Pierwszy Urząd Skarbowy Łódź-Bałuty",
  "Drugi Urząd Skarbowy Łódź-Bałuty",
  "Pierwszy Urząd Skarbowy Łódź-Górna",
  "Drugi Urząd Skarbowy Łódź-Górna",
  "Urząd Skarbowy Łódź-Polesie",
  "Urząd Skarbowy Łódź-Śródmieście",
  "Urząd Skarbowy Łódź-Widzew",
  "Urząd Skarbowy w Opocznie",
  "Urząd Skarbowy w Pabianicach",
  "Urząd Skarbowy w Piotrkowie Trybunalskim",
  "Urząd Skarbowy w Poddębicach",
  "Urząd Skarbowy w Radomsku",
  "Urząd Skarbowy w Rawie Mazowieckiej",
  "Urząd Skarbowy w Sieradzu",
  "Urząd Skarbowy w Skierniewicach",
  "Urząd Skarbowy w Tomaszowie Mazowieckim",
  "Urząd Skarbowy w Wieluniu",
  "Urząd Skarbowy w Zduńskiej Woli",
  "Urząd Skarbowy w Zgierzu",
  "Urząd Skarbowy w Wieruszowie",
  "Urząd Skarbowy w Łęczycy",
  "Urząd Skarbowy w Pajęcznie",
  "Łódzki Urząd Skarbowy w Łodzi",
  "Urząd Skarbowy w Bochni",
  "Urząd Skarbowy w Brzesku",
  "Urząd Skarbowy w Chrzanowie",
  "Urząd Skarbowy w Dąbrowie Tarnowskiej",
  "Urząd Skarbowy w Gorlicach",
  "Pierwszy Urząd Skarbowy w Krakowie",
  "Urząd Skarbowy Kraków-Krowodrza",
  "Urząd Skarbowy Kraków-Nowa Huta",
  "Urząd Skarbowy Kraków-Podgórze",
  "Urząd Skarbowy Kraków-Prądnik",
  "Urząd Skarbowy Kraków-Stare Miasto",
  "Urząd Skarbowy Kraków-Śródmieście",
  "Urząd Skarbowy w Limanowej",
  "Urząd Skarbowy w Miechowie",
  "Urząd Skarbowy w Myślenicach",
  "Urząd Skarbowy w Nowym Sączu",
  "Urząd Skarbowy w Nowym Targu",
  "Urząd Skarbowy w Olkuszu",
  "Urząd Skarbowy w Oświęcimiu",
  "Urząd Skarbowy w Proszowicach",
  "Urząd Skarbowy w Suchej Beskidzkiej",
  "Pierwszy Urząd Skarbowy w Tarnowie",
  "Drugi Urząd Skarbowy w Tarnowie",
  "Urząd Skarbowy w Wadowicach",
  "Urząd Skarbowy w Wieliczce",
  "Urząd Skarbowy w Zakopanem",
  "Drugi Urząd Skarbowy Kraków",
  "Małopolski Urząd Skarbowy w Krakowie",
  "Urząd Skarbowy w Białobrzegach",
  "Urząd Skarbowy w Ciechanowie",
  "Urząd Skarbowy w Garwolinie",
  "Urząd Skarbowy w Gostyninie",
  "Urząd Skarbowy w Grodzisku Mazowieckim",
  "Urząd Skarbowy w Grójcu",
  "Urząd Skarbowy w Kozienicach",
  "Urząd Skarbowy w Legionowie",
  "Urząd Skarbowy w Łosicach",
  "Urząd Skarbowy w Makowie Mazowieckim",
  "Urząd Skarbowy w Mińsku Mazowieckim",
  "Urząd Skarbowy w Mławie",
  "Urząd Skarbowy w Nowym Dworze Mazowieckim",
  "Urząd Skarbowy w Ostrołęce",
  "Urząd Skarbowy w Ostrowi Mazowieckiej",
  "Urząd Skarbowy w Otwocku",
  "Urząd Skarbowy w Piasecznie",
  "Urząd Skarbowy w Płocku",
  "Urząd Skarbowy w Płońsku",
  "Urząd Skarbowy w Pruszkowie",
  "Urząd Skarbowy w Przasnyszu",
  "Urząd Skarbowy w Pułtusku",
  "Pierwszy Urząd Skarbowy w Radomiu",
  "Drugi Urząd Skarbowy w Radomiu",
  "Urząd Skarbowy w Siedlcach",
  "Urząd Skarbowy w Sierpcu",
  "Urząd Skarbowy w Sochaczewie",
  "Urząd Skarbowy w Sokołowie Podlaskim",
  "Urząd Skarbowy w Szydłowcu",
  "Urząd Skarbowy Warszawa-Bemowo",
  "Urząd Skarbowy Warszawa-Bielany",
  "Urząd Skarbowy Warszawa-Mokotów",
  "Urząd Skarbowy Warszawa-Praga",
  "Pierwszy Urząd Skarbowy Warszawa-Śródmieście",
  "Drugi Urząd Skarbowy Warszawa-Śródmieście",
  "Urząd Skarbowy Warszawa-Targówek",
  "Urząd Skarbowy Warszawa-Ursynów",
  "Urząd Skarbowy Warszawa-Wawer",
  "Urząd Skarbowy Warszawa-Wola",
  "Urząd Skarbowy w Węgrowie",
  "Urząd Skarbowy w Wołominie",
  "Urząd Skarbowy w Wyszkowie",
  "Urząd Skarbowy w Zwoleniu",
  "Urząd Skarbowy w Żurominie",
  "Urząd Skarbowy w Żyrardowie",
  "Urząd Skarbowy w Lipsku",
  "Urząd Skarbowy w Przysusze",
  "Trzeci Urząd Skarbowy Warszawa-Śródmieście",
  "Pierwszy Mazowiecki Urząd Skarbowy w Warszawie",
  "Drugi Mazowiecki Urząd Skarbowy w Warszawie",
  "Trzeci Mazowiecki Urząd Skarbowy w Radomiu",
  "Urząd Skarbowy w Brzegu",
  "Urząd Skarbowy w Głubczycach",
  "Urząd Skarbowy w Kędzierzynie-Koźlu",
  "Urząd Skarbowy w Kluczborku",
  "Urząd Skarbowy w Namysłowie",
  "Urząd Skarbowy w Nysie",
  "Urząd Skarbowy w Oleśnie",
  "Pierwszy Urząd Skarbowy w Opolu",
  "Drugi Urząd Skarbowy w Opolu",
  "Urząd Skarbowy w Prudniku",
  "Urząd Skarbowy w Strzelcach Opolskich",
  "Urząd Skarbowy w Krapkowicach",
  "Opolski Urząd Skarbowy w Opolu",
  "Urząd Skarbowy w Brzozowie",
  "Urząd Skarbowy w Dębicy",
  "Urząd Skarbowy w Jarosławiu",
  "Urząd Skarbowy w Jaśle",
  "Urząd Skarbowy w Kolbuszowej",
  "Urząd Skarbowy w Krośnie",
  "Urząd Skarbowy w Lesku",
  "Urząd Skarbowy w Leżajsku",
  "Urząd Skarbowy w Lubaczowie",
  "Urząd Skarbowy w Łańcucie",
  "Urząd Skarbowy w Mielcu",
  "Urząd Skarbowy w Przemyślu",
  "Urząd Skarbowy w Przeworsku",
  "Urząd Skarbowy w Ropczycach",
  "Pierwszy Urząd Skarbowy w Rzeszowie",
  "Urząd Skarbowy w Sanoku",
  "Urząd Skarbowy w Stalowej Woli",
  "Urząd Skarbowy w Strzyżowie",
  "Urząd Skarbowy w Tarnobrzegu",
  "Urząd Skarbowy w Ustrzykach Dolnych",
  "Drugi Urząd Skarbowy w Rzeszowie",
  "Urząd Skarbowy w Nisku",
  "Podkarpacki Urząd Skarbowy w Rzeszowie",
  "Urząd Skarbowy w Augustowie",
  "Pierwszy Urząd Skarbowy w Białymstoku",
  "Drugi Urząd Skarbowy w Białymstoku",
  "Urząd Skarbowy w Bielsku Podlaskim",
  "Urząd Skarbowy w Grajewie",
  "Urząd Skarbowy w Kolnie",
  "Urząd Skarbowy w Łomży",
  "Urząd Skarbowy w Mońkach",
  "Urząd Skarbowy w Siemiatyczach",
  "Urząd Skarbowy w Sokółce",
  "Urząd Skarbowy w Suwałkach",
  "Urząd Skarbowy w Wysokiem Mazowieckiem",
  "Urząd Skarbowy w Zambrowie",
  "Urząd Skarbowy w Hajnówce",
  "Podlaski Urząd Skarbowy w Białymstoku",
  "Urząd Skarbowy w Bytowie",
  "Urząd Skarbowy w Chojnicach",
  "Urząd Skarbowy w Człuchowie",
  "Pierwszy Urząd Skarbowy w Gdańsku",
  "Drugi Urząd Skarbowy w Gdańsku",
  "Trzeci Urząd Skarbowy w Gdańsku",
  "Pierwszy Urząd Skarbowy w Gdyni",
  "Drugi Urząd Skarbowy w Gdyni",
  "Urząd Skarbowy w Kartuzach",
  "Urząd Skarbowy w Kościerzynie",
  "Urząd Skarbowy w Kwidzynie",
  "Urząd Skarbowy w Lęborku",
  "Urząd Skarbowy w Malborku",
  "Urząd Skarbowy w Pucku",
  "Urząd Skarbowy w Słupsku",
  "Urząd Skarbowy w Sopocie",
  "Urząd Skarbowy w Starogardzie Gdańskim",
  "Urząd Skarbowy w Tczewie",
  "Urząd Skarbowy w Wejherowie",
  "Urząd Skarbowy w Pruszczu Gdańskim",
  "Pomorski Urząd Skarbowy w Gdańsku",
  "Urząd Skarbowy w Będzinie",
  "Pierwszy Urząd Skarbowy w Bielsku-Białej",
  "Drugi Urząd Skarbowy w Bielsku-Białej",
  "Urząd Skarbowy w Bytomiu",
  "Urząd Skarbowy w Chorzowie",
  "Urząd Skarbowy w Cieszynie",
  "Urząd Skarbowy w Czechowicach-Dziedzicach",
  "Pierwszy Urząd Skarbowy w Częstochowie",
  "Drugi Urząd Skarbowy w Częstochowie",
  "Urząd Skarbowy w Dąbrowie Górniczej",
  "Pierwszy Urząd Skarbowy w Gliwicach",
  "Drugi Urząd Skarbowy w Gliwicach",
  "Urząd Skarbowy w Jastrzębiu-Zdroju",
  "Urząd Skarbowy w Jaworznie",
  "Pierwszy Urząd Skarbowy w Katowicach",
  "Drugi Urząd Skarbowy w Katowicach",
  "Urząd Skarbowy w Kłobucku",
  "Urząd Skarbowy w Lublińcu",
  "Urząd Skarbowy w Mikołowie",
  "Urząd Skarbowy w Mysłowicach",
  "Urząd Skarbowy w Myszkowie",
  "Urząd Skarbowy w Piekarach Śląskich",
  "Urząd Skarbowy w Pszczynie",
  "Urząd Skarbowy w Raciborzu",
  "Urząd Skarbowy w Rudzie Śląskiej",
  "Urząd Skarbowy w Rybniku",
  "Urząd Skarbowy w Siemianowicach Śląskich",
  "Urząd Skarbowy w Sosnowcu",
  "Urząd Skarbowy w Tarnowskich Górach",
  "Urząd Skarbowy w Tychach",
  "Urząd Skarbowy w Wodzisławiu Śląskim",
  "Urząd Skarbowy w Zabrzu",
  "Urząd Skarbowy w Zawierciu",
  "Urząd Skarbowy w Żorach",
  "Urząd Skarbowy w Żywcu",
  "Pierwszy Śląski Urząd Skarbowy w Sosnowcu",
  "Drugi Śląski Urząd Skarbowy w Bielsku-Białej",
  "Urząd Skarbowy w Busku-Zdroju",
  "Urząd Skarbowy w Jędrzejowie",
  "Pierwszy Urząd Skarbowy w Kielcach",
  "Drugi Urząd Skarbowy w Kielcach",
  "Urząd Skarbowy w Końskich",
  "Urząd Skarbowy w Opatowie",
  "Urząd Skarbowy w Ostrowcu Świętokrzyskim",
  "Urząd Skarbowy w Pińczowie",
  "Urząd Skarbowy w Sandomierzu",
  "Urząd Skarbowy w Skarżysku-Kamiennej",
  "Urząd Skarbowy w Starachowicach",
  "Urząd Skarbowy w Staszowie",
  "Urząd Skarbowy w Kazimierzy Wielkiej",
  "Urząd Skarbowy we Włoszczowie",
  "Świętokrzyski Urząd Skarbowy w Kielcach",
  "Urząd Skarbowy w Bartoszycach",
  "Urząd Skarbowy w Braniewie",
  "Urząd Skarbowy w Działdowie",
  "Urząd Skarbowy w Elblągu",
  "Urząd Skarbowy w Ełku",
  "Urząd Skarbowy w Giżycku",
  "Urząd Skarbowy w Iławie",
  "Urząd Skarbowy w Kętrzynie",
  "Urząd Skarbowy w Nidzicy",
  "Urząd Skarbowy w Nowym Mieście Lubawskim",
  "Urząd Skarbowy w Olecku",
  "Urząd Skarbowy w Olsztynie",
  "Urząd Skarbowy w Ostródzie",
  "Urząd Skarbowy w Piszu",
  "Urząd Skarbowy w Szczytnie",
  "Warmińsko-Mazurski Urząd Skarbowy w Olsztynie",
  "Urząd Skarbowy w Czarnkowie",
  "Urząd Skarbowy w Gnieźnie",
  "Urząd Skarbowy w Gostyniu",
  "Urząd Skarbowy w Grodzisku Wielkopolskim",
  "Urząd Skarbowy w Jarocinie",
  "Pierwszy Urząd Skarbowy w Kaliszu",
  "Drugi Urząd Skarbowy w Kaliszu",
  "Urząd Skarbowy w Kępnie",
  "Urząd Skarbowy w Kole",
  "Urząd Skarbowy w Koninie",
  "Urząd Skarbowy w Kościanie",
  "Urząd Skarbowy w Krotoszynie",
  "Urząd Skarbowy w Lesznie",
  "Urząd Skarbowy w Międzychodzie",
  "Urząd Skarbowy w Nowym Tomyślu",
  "Urząd Skarbowy w Ostrowie Wielkopolskim",
  "Urząd Skarbowy w Ostrzeszowie",
  "Urząd Skarbowy w Pile",
  "Urząd Skarbowy Poznań-Grunwald",
  "Urząd Skarbowy Poznań-Jeżyce",
  "Urząd Skarbowy Poznań-Nowe Miasto",
  "Pierwszy Urząd Skarbowy w Poznaniu",
  "Urząd Skarbowy Poznań-Winogrady",
  "Urząd Skarbowy Poznań-Wilda",
  "Urząd Skarbowy w Rawiczu",
  "Urząd Skarbowy w Słupcy",
  "Urząd Skarbowy w Szamotułach",
  "Urząd Skarbowy w Śremie",
  "Urząd Skarbowy w Środzie Wielkopolskiej",
  "Urząd Skarbowy w Turku",
  "Urząd Skarbowy w Wągrowcu",
  "Urząd Skarbowy w Wolsztynie",
  "Urząd Skarbowy we Wrześni",
  "Urząd Skarbowy w Złotowie",
  "Urząd Skarbowy w Chodzieży",
  "Urząd Skarbowy w Obornikach",
  "Urząd Skarbowy w Pleszewie",
  "Pierwszy Wielkopolski Urząd Skarbowy w Poznaniu",
  "Drugi Wielkopolski Urząd Skarbowy w Kaliszu",
  "Urząd Skarbowy w Białogardzie",
  "Urząd Skarbowy w Choszcznie",
  "Urząd Skarbowy w Drawsku Pomorskim",
  "Urząd Skarbowy w Goleniowie",
  "Urząd Skarbowy w Gryficach",
  "Urząd Skarbowy w Gryfinie",
  "Urząd Skarbowy w Kamieniu Pomorskim",
  "Urząd Skarbowy w Kołobrzegu",
  "Pierwszy Urząd Skarbowy w Koszalinie",
  "Drugi Urząd Skarbowy w Koszalinie",
  "Urząd Skarbowy w Myśliborzu",
  "Urząd Skarbowy w Pyrzycach",
  "Urząd Skarbowy w Stargardzie Szczecińskim",
  "Pierwszy Urząd Skarbowy w Szczecinie",
  "Drugi Urząd Skarbowy w Szczecinie",
  "Trzeci Urząd Skarbowy w Szczecinie",
  "Urząd Skarbowy w Szczecinku",
  "Urząd Skarbowy w Świnoujściu",
  "Urząd Skarbowy w Wałczu",
  "Zachodniopomorski Urząd Skarbowy w Szczecinie",
];
